### ISSUE TITLE
[Question] modeIndex parameter?

### ISSUE THREAD

**Issue by jzecca** [YaroslavSl/llrp-ts#1]
Hi,
I just discovered this lib, and it looks very interesting 😃 

I just have a little question about the `modeIndex` parameter:
Does it correspond to the  reader mode [(as described in the Impinj documentation here)](https://support.impinj.com/hc/en-us/articles/360000046899-Reader-Modes-Made-Easy)?
Is it 0 for Max Throughput, 1 for Hybrid, etc.?

Or is it something else?

**Comment by YaroslavSl** [comment]
Hi Jérôme Zecca,

Yes, It is. The parameter corresponds to the impinj parameter.
